### ISSUE TITLE
it didnt work

### ISSUE THREAD

**Issue by splootybean** [GabeTheFirst/QuerryNetworking#2]
it just didnt work wtf

**Comment by SlimePuppy8** [comment]
sucks to suck

**Comment by splootybean** [comment]
> sucks to suck

sucks to live at 123 silly street

**Comment by GabeTheFirst** [comment]
> sucks to suck

> sucks to live at 123 silly street

I'm going to close this issue now 🐱🎉

**Comment by GabeTheFirst** [comment]
Silly (it already works, splootybean was JOKING 🎉) 😹
